version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: demo-app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-demo_app}
      POSTGRES_USER: ${DB_USER:-demo_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-demo_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-demo_user} -d ${DB_NAME:-demo_app_dev}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: